import { SoulProfile } from './profiles';

/**
 * Generate the SOUL.md content to inject into IDE rules
 */
export function generateSoulMd(profile: SoulProfile): string {
  const bar = (v: number, w = 15) => {
    const f = Math.round((v / 100) * w);
    return '█'.repeat(f) + '░'.repeat(w - f) + ` ${v}`;
  };

  return `# ⬡ MnemoForge Soul Protocol — ${profile.name} (${profile.archetype})

> ${profile.tagline}

**Active since:** ${new Date().toISOString().slice(0, 10)}
**Injected by:** mnemoforge soul inject
**Tone:** ${profile.tone}
**Tags:** ${profile.tags.join(', ')}

---

## Behavior Matrix (OCEAN)

| Trait            | Score | Level |
|------------------|-------|-------|
| Openness         | ${profile.ocean.openness}    | ${bar(profile.ocean.openness)} |
| Conscientiousness| ${profile.ocean.conscientiousness}    | ${bar(profile.ocean.conscientiousness)} |
| Extraversion     | ${profile.ocean.extraversion}    | ${bar(profile.ocean.extraversion)} |
| Agreeableness    | ${profile.ocean.agreeableness}    | ${bar(profile.ocean.agreeableness)} |
| Neuroticism      | ${profile.ocean.neuroticism}    | ${bar(profile.ocean.neuroticism)} |

---

## Directives

${profile.directives.map((d, i) => `${i + 1}. ${d}`).join('\n')}

---

*This file was generated by MnemoForge CLI. To switch profiles: \`mnemoforge soul switch\`*
*To view all profiles: \`mnemoforge soul dex\`*
`;
}

/**
 * Resolve the SOUL.md injection path for a given IDE
 */
export function getSoulPath(ide: string): string | null {
  const home = process.env.HOME ?? process.env.USERPROFILE ?? '';
  const appData = process.env.APPDATA ?? '';

  const map: Record<string, string> = {
    cursor:        `${home}/.cursor/rules/SOUL.md`,
    claudedesktop: `${appData}/Claude/SOUL.md`,
    claudecode:    `${home}/.claude/SOUL.md`,
    vscode:        '.vscode/SOUL.md',
    windsurf:      `${home}/.codeium/windsurf/SOUL.md`,
    antigravity:   `${home}/.gemini/antigravity/SOUL.md`,
  };

  const key = ide.replace(/[\s_\-]/g, '').toLowerCase();
  for (const [k, v] of Object.entries(map)) {
    if (key.includes(k)) return v;
  }
  return null;
}
